/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { Public } from "../../decorators/public.decorator";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CreateChannelArgs } from "./CreateChannelArgs";
import { UpdateChannelArgs } from "./UpdateChannelArgs";
import { DeleteChannelArgs } from "./DeleteChannelArgs";
import { ChannelCountArgs } from "./ChannelCountArgs";
import { ChannelFindManyArgs } from "./ChannelFindManyArgs";
import { ChannelFindUniqueArgs } from "./ChannelFindUniqueArgs";
import { Channel } from "./Channel";
import { User } from "../../user/base/User";
import { ChannelService } from "../channel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Channel)
export class ChannelResolverBase {
  constructor(
    protected readonly service: ChannelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @graphql.Query(() => MetaQueryPayload)
  async _channelsMeta(
    @graphql.Args() args: ChannelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @Public()
  @graphql.Query(() => [Channel])
  async channels(
    @graphql.Args() args: ChannelFindManyArgs
  ): Promise<Channel[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Channel, { nullable: true })
  async channel(
    @graphql.Args() args: ChannelFindUniqueArgs
  ): Promise<Channel | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Channel)
  @nestAccessControl.UseRoles({
    resource: "Channel",
    action: "create",
    possession: "any",
  })
  async createChannel(
    @graphql.Args() args: CreateChannelArgs
  ): Promise<Channel> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        Members: {
          connect: args.data.Members,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Channel)
  @nestAccessControl.UseRoles({
    resource: "Channel",
    action: "update",
    possession: "any",
  })
  async updateChannel(
    @graphql.Args() args: UpdateChannelArgs
  ): Promise<Channel | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          Members: {
            connect: args.data.Members,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Channel)
  @nestAccessControl.UseRoles({
    resource: "Channel",
    action: "delete",
    possession: "any",
  })
  async deleteChannel(
    @graphql.Args() args: DeleteChannelArgs
  ): Promise<Channel | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "members",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async resolveFieldMembers(
    @graphql.Parent() parent: Channel
  ): Promise<User | null> {
    const result = await this.service.getMembers(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
